### ISSUE TITLE
Initialize Rust Project

### ISSUE THREAD

**Issue by richarddushime** [richarddushime/Bitcoin-bank#1]
## Set up the initial Rust project structure for the backend
**Tasks:**

- [x] Create a new Rust project.
- [x] Configure project dependencies and settings.

**Comment by 448-OG** [comment]
The first task has been completed in https://github.com/richarddushime/Bitcoin-bank/commit/e9d1047e8d17c46c0169c891456bc14b6d73a057

**Comment by 448-OG** [comment]
The second task has been completed in commit - https://github.com/richarddushime/Bitcoin-bank/commit/a4615f4fad1e1806f1e93688dacaaa65e76a43c9
