### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by 448-OG** [richarddushime/Bitcoin-bank#12]
Create a simple key value store to persist state using sled.rs

**Comment by ItoroD** [comment]
hey @448-OG
I have created an SQLite DB for starters. So maybe you can break the issue down with checkboxes I suggest

- SQLite db to make sure basic functionality is working
- then transition to sled.rs / hashcorp vault - because security is a big part of our project

**Comment by richarddushime** [comment]
I hope this is Done and can be closed as completed
